/**
 * generated by Xtext
 */
package dk.itu.smdp.group19.ui.contentassist;

import dk.itu.smdp.group19.ui.contentassist.AbstractSurveyDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SurveyDSLProposalProvider extends AbstractSurveyDSLProposalProvider {
}
