/*
* generated by Xtext
*/
package dk.itu.smdp.group19;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SurveyDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.smdp.group19.ui.internal.SurveyDSLActivator.getInstance().getInjector("dk.itu.smdp.group19.SurveyDSL");
	}
	
}
