/*
* generated by Xtext
*/
package dk.itu.smdp.group19.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SurveyDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SurveyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Survey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartSurveyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTitleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTitleEStringParserRuleCall_2_0 = (RuleCall)cTitleAssignment_2.eContents().get(0);
		private final Keyword cPagesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPagesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPagesPageParserRuleCall_4_0 = (RuleCall)cPagesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPagesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPagesPageParserRuleCall_5_1_0 = (RuleCall)cPagesAssignment_5_1.eContents().get(0);
		private final Keyword cEndSurveyKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Survey:
		//	"start survey" "title:" title=EString "pages:" pages+=Page ("," pages+=Page)* "end survey";
		public ParserRule getRule() { return rule; }

		//"start survey" "title:" title=EString "pages:" pages+=Page ("," pages+=Page)* "end survey"
		public Group getGroup() { return cGroup; }

		//"start survey"
		public Keyword getStartSurveyKeyword_0() { return cStartSurveyKeyword_0; }

		//"title:"
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }

		//title=EString
		public Assignment getTitleAssignment_2() { return cTitleAssignment_2; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_2_0() { return cTitleEStringParserRuleCall_2_0; }

		//"pages:"
		public Keyword getPagesKeyword_3() { return cPagesKeyword_3; }

		//pages+=Page
		public Assignment getPagesAssignment_4() { return cPagesAssignment_4; }

		//Page
		public RuleCall getPagesPageParserRuleCall_4_0() { return cPagesPageParserRuleCall_4_0; }

		//("," pages+=Page)*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//pages+=Page
		public Assignment getPagesAssignment_5_1() { return cPagesAssignment_5_1; }

		//Page
		public RuleCall getPagesPageParserRuleCall_5_1_0() { return cPagesPageParserRuleCall_5_1_0; }

		//"end survey"
		public Keyword getEndSurveyKeyword_6() { return cEndSurveyKeyword_6; }
	}

	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cQuestionPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDescriptionPageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cResultPageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Page:
		//	QuestionPage | DescriptionPage | ResultPage;
		public ParserRule getRule() { return rule; }

		//QuestionPage | DescriptionPage | ResultPage
		public Alternatives getAlternatives() { return cAlternatives; }

		//QuestionPage
		public RuleCall getQuestionPageParserRuleCall_0() { return cQuestionPageParserRuleCall_0; }

		//DescriptionPage
		public RuleCall getDescriptionPageParserRuleCall_1() { return cDescriptionPageParserRuleCall_1; }

		//ResultPage
		public RuleCall getResultPageParserRuleCall_2() { return cResultPageParserRuleCall_2; }
	}

	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFreetextQuestionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSingleChoiceQuestionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMultiChoiceQuestionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Question:
		//	FreetextQuestion | SingleChoiceQuestion | MultiChoiceQuestion;
		public ParserRule getRule() { return rule; }

		//FreetextQuestion | SingleChoiceQuestion | MultiChoiceQuestion
		public Alternatives getAlternatives() { return cAlternatives; }

		//FreetextQuestion
		public RuleCall getFreetextQuestionParserRuleCall_0() { return cFreetextQuestionParserRuleCall_0; }

		//SingleChoiceQuestion
		public RuleCall getSingleChoiceQuestionParserRuleCall_1() { return cSingleChoiceQuestionParserRuleCall_1; }

		//MultiChoiceQuestion
		public RuleCall getMultiChoiceQuestionParserRuleCall_2() { return cMultiChoiceQuestionParserRuleCall_2; }
	}

	public class DependencyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dependency");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAndParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOrParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAnswerRefParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Dependency:
		//	And | Or | AnswerRef;
		public ParserRule getRule() { return rule; }

		//And | Or | AnswerRef
		public Alternatives getAlternatives() { return cAlternatives; }

		//And
		public RuleCall getAndParserRuleCall_0() { return cAndParserRuleCall_0; }

		//Or
		public RuleCall getOrParserRuleCall_1() { return cOrParserRuleCall_1; }

		//AnswerRef
		public RuleCall getAnswerRefParserRuleCall_2() { return cAnswerRefParserRuleCall_2; }
	}

	public class AnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Answer");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cChoiceAnswerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFreetextAnswerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Answer:
		//	ChoiceAnswer | FreetextAnswer;
		public ParserRule getRule() { return rule; }

		//ChoiceAnswer | FreetextAnswer
		public Alternatives getAlternatives() { return cAlternatives; }

		//ChoiceAnswer
		public RuleCall getChoiceAnswerParserRuleCall_0() { return cChoiceAnswerParserRuleCall_0; }

		//FreetextAnswer
		public RuleCall getFreetextAnswerParserRuleCall_1() { return cFreetextAnswerParserRuleCall_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class QuestionPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QuestionPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddQuestionPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTitleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTitleEStringParserRuleCall_2_0 = (RuleCall)cTitleAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTextAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_3_1_0 = (RuleCall)cTextAssignment_3_1.eContents().get(0);
		private final Keyword cQuestionsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cQuestionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cQuestionsQuestionParserRuleCall_5_0 = (RuleCall)cQuestionsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cQuestionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cQuestionsQuestionParserRuleCall_6_1_0 = (RuleCall)cQuestionsAssignment_6_1.eContents().get(0);
		
		////Page_Impl returns Page:
		////	'Page'
		////	'{'
		////		'title' title=EString
		////		('text' text=EString)?
		////	'}';
		//QuestionPage:
		//	"add question page" "title:" title=EString ("text:" text=EString)? "questions:" questions+=Question (","
		//	questions+=Question)*;
		public ParserRule getRule() { return rule; }

		//"add question page" "title:" title=EString ("text:" text=EString)? "questions:" questions+=Question (","
		//questions+=Question)*
		public Group getGroup() { return cGroup; }

		//"add question page"
		public Keyword getAddQuestionPageKeyword_0() { return cAddQuestionPageKeyword_0; }

		//"title:"
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }

		//title=EString
		public Assignment getTitleAssignment_2() { return cTitleAssignment_2; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_2_0() { return cTitleEStringParserRuleCall_2_0; }

		//("text:" text=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"text:"
		public Keyword getTextKeyword_3_0() { return cTextKeyword_3_0; }

		//text=EString
		public Assignment getTextAssignment_3_1() { return cTextAssignment_3_1; }

		//EString
		public RuleCall getTextEStringParserRuleCall_3_1_0() { return cTextEStringParserRuleCall_3_1_0; }

		//"questions:"
		public Keyword getQuestionsKeyword_4() { return cQuestionsKeyword_4; }

		//questions+=Question
		public Assignment getQuestionsAssignment_5() { return cQuestionsAssignment_5; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_5_0() { return cQuestionsQuestionParserRuleCall_5_0; }

		//("," questions+=Question)*
		public Group getGroup_6() { return cGroup_6; }

		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }

		//questions+=Question
		public Assignment getQuestionsAssignment_6_1() { return cQuestionsAssignment_6_1; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_6_1_0() { return cQuestionsQuestionParserRuleCall_6_1_0; }
	}

	public class DescriptionPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DescriptionPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddDescriptionPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTitleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTitleEStringParserRuleCall_2_0 = (RuleCall)cTitleAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTextAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_3_1_0 = (RuleCall)cTextAssignment_3_1.eContents().get(0);
		
		//DescriptionPage:
		//	"add description page" "title:" title=EString ("text:" text=EString)?;
		public ParserRule getRule() { return rule; }

		//"add description page" "title:" title=EString ("text:" text=EString)?
		public Group getGroup() { return cGroup; }

		//"add description page"
		public Keyword getAddDescriptionPageKeyword_0() { return cAddDescriptionPageKeyword_0; }

		//"title:"
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }

		//title=EString
		public Assignment getTitleAssignment_2() { return cTitleAssignment_2; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_2_0() { return cTitleEStringParserRuleCall_2_0; }

		//("text:" text=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"text:"
		public Keyword getTextKeyword_3_0() { return cTextKeyword_3_0; }

		//text=EString
		public Assignment getTextAssignment_3_1() { return cTextAssignment_3_1; }

		//EString
		public RuleCall getTextEStringParserRuleCall_3_1_0() { return cTextEStringParserRuleCall_3_1_0; }
	}

	public class ResultPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResultPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddResultPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTitleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTitleEStringParserRuleCall_2_0 = (RuleCall)cTitleAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTextAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_3_1_0 = (RuleCall)cTextAssignment_3_1.eContents().get(0);
		
		//ResultPage:
		//	"add result page" "title:" title=EString ("text:" text=EString)?;
		public ParserRule getRule() { return rule; }

		//"add result page" "title:" title=EString ("text:" text=EString)?
		public Group getGroup() { return cGroup; }

		//"add result page"
		public Keyword getAddResultPageKeyword_0() { return cAddResultPageKeyword_0; }

		//"title:"
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }

		//title=EString
		public Assignment getTitleAssignment_2() { return cTitleAssignment_2; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_2_0() { return cTitleEStringParserRuleCall_2_0; }

		//("text:" text=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"text:"
		public Keyword getTextKeyword_3_0() { return cTextKeyword_3_0; }

		//text=EString
		public Assignment getTextAssignment_3_1() { return cTextAssignment_3_1; }

		//EString
		public RuleCall getTextEStringParserRuleCall_3_1_0() { return cTextEStringParserRuleCall_3_1_0; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		////Question_Impl returns Question:
		////	optional?='optional'
		////	'Question'
		////	'{'
		////	'text' text=EString
		////	('requires' requires=Dependency)?
		////	'}';
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class FreetextQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FreetextQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOptionalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOptionalOptionalKeyword_1_0 = (Keyword)cOptionalAssignment_1.eContents().get(0);
		private final Keyword cFreetextQuestionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextEStringParserRuleCall_4_0 = (RuleCall)cTextAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRequiresKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRequiresAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRequiresDependencyParserRuleCall_5_1_0 = (RuleCall)cRequiresAssignment_5_1.eContents().get(0);
		private final Keyword cAnswersKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAnswersAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAnswersFreetextAnswerParserRuleCall_7_0 = (RuleCall)cAnswersAssignment_7.eContents().get(0);
		
		//FreetextQuestion:
		//	"add" optional?="optional"? "freetext question" "text:" text=EString ("requires:" requires=Dependency)? "answers:"
		//	answers=FreetextAnswer;
		public ParserRule getRule() { return rule; }

		//"add" optional?="optional"? "freetext question" "text:" text=EString ("requires:" requires=Dependency)? "answers:"
		//answers=FreetextAnswer
		public Group getGroup() { return cGroup; }

		//"add"
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }

		//optional?="optional"?
		public Assignment getOptionalAssignment_1() { return cOptionalAssignment_1; }

		//"optional"
		public Keyword getOptionalOptionalKeyword_1_0() { return cOptionalOptionalKeyword_1_0; }

		//"freetext question"
		public Keyword getFreetextQuestionKeyword_2() { return cFreetextQuestionKeyword_2; }

		//"text:"
		public Keyword getTextKeyword_3() { return cTextKeyword_3; }

		//text=EString
		public Assignment getTextAssignment_4() { return cTextAssignment_4; }

		//EString
		public RuleCall getTextEStringParserRuleCall_4_0() { return cTextEStringParserRuleCall_4_0; }

		//("requires:" requires=Dependency)?
		public Group getGroup_5() { return cGroup_5; }

		//"requires:"
		public Keyword getRequiresKeyword_5_0() { return cRequiresKeyword_5_0; }

		//requires=Dependency
		public Assignment getRequiresAssignment_5_1() { return cRequiresAssignment_5_1; }

		//Dependency
		public RuleCall getRequiresDependencyParserRuleCall_5_1_0() { return cRequiresDependencyParserRuleCall_5_1_0; }

		//"answers:"
		public Keyword getAnswersKeyword_6() { return cAnswersKeyword_6; }

		//answers=FreetextAnswer
		public Assignment getAnswersAssignment_7() { return cAnswersAssignment_7; }

		//FreetextAnswer
		public RuleCall getAnswersFreetextAnswerParserRuleCall_7_0() { return cAnswersFreetextAnswerParserRuleCall_7_0; }
	}

	public class SingleChoiceQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SingleChoiceQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOptionalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOptionalOptionalKeyword_1_0 = (Keyword)cOptionalAssignment_1.eContents().get(0);
		private final Keyword cSingleChoiceQuestionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextEStringParserRuleCall_4_0 = (RuleCall)cTextAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRequiresKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRequiresAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRequiresDependencyParserRuleCall_5_1_0 = (RuleCall)cRequiresAssignment_5_1.eContents().get(0);
		private final Keyword cAnswersKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAnswersAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAnswersAnswerParserRuleCall_7_0 = (RuleCall)cAnswersAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAnswersAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAnswersAnswerParserRuleCall_8_1_0 = (RuleCall)cAnswersAssignment_8_1.eContents().get(0);
		
		//SingleChoiceQuestion:
		//	"add" optional?="optional"? "single choice question" "text:" text=EString ("requires:" requires=Dependency)?
		//	"answers:" answers+=Answer ("," answers+=Answer)*;
		public ParserRule getRule() { return rule; }

		//"add" optional?="optional"? "single choice question" "text:" text=EString ("requires:" requires=Dependency)? "answers:"
		//answers+=Answer ("," answers+=Answer)*
		public Group getGroup() { return cGroup; }

		//"add"
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }

		//optional?="optional"?
		public Assignment getOptionalAssignment_1() { return cOptionalAssignment_1; }

		//"optional"
		public Keyword getOptionalOptionalKeyword_1_0() { return cOptionalOptionalKeyword_1_0; }

		//"single choice question"
		public Keyword getSingleChoiceQuestionKeyword_2() { return cSingleChoiceQuestionKeyword_2; }

		//"text:"
		public Keyword getTextKeyword_3() { return cTextKeyword_3; }

		//text=EString
		public Assignment getTextAssignment_4() { return cTextAssignment_4; }

		//EString
		public RuleCall getTextEStringParserRuleCall_4_0() { return cTextEStringParserRuleCall_4_0; }

		//("requires:" requires=Dependency)?
		public Group getGroup_5() { return cGroup_5; }

		//"requires:"
		public Keyword getRequiresKeyword_5_0() { return cRequiresKeyword_5_0; }

		//requires=Dependency
		public Assignment getRequiresAssignment_5_1() { return cRequiresAssignment_5_1; }

		//Dependency
		public RuleCall getRequiresDependencyParserRuleCall_5_1_0() { return cRequiresDependencyParserRuleCall_5_1_0; }

		//"answers:"
		public Keyword getAnswersKeyword_6() { return cAnswersKeyword_6; }

		//answers+=Answer
		public Assignment getAnswersAssignment_7() { return cAnswersAssignment_7; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_7_0() { return cAnswersAnswerParserRuleCall_7_0; }

		//("," answers+=Answer)*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//answers+=Answer
		public Assignment getAnswersAssignment_8_1() { return cAnswersAssignment_8_1; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_8_1_0() { return cAnswersAnswerParserRuleCall_8_1_0; }
	}

	public class MultiChoiceQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultiChoiceQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOptionalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOptionalOptionalKeyword_1_0 = (Keyword)cOptionalAssignment_1.eContents().get(0);
		private final Keyword cMultiChoiceQuestionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextEStringParserRuleCall_4_0 = (RuleCall)cTextAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRequiresKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRequiresAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRequiresDependencyParserRuleCall_5_1_0 = (RuleCall)cRequiresAssignment_5_1.eContents().get(0);
		private final Keyword cAnswersKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAnswersAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAnswersAnswerParserRuleCall_7_0 = (RuleCall)cAnswersAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAnswersAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAnswersAnswerParserRuleCall_8_1_0 = (RuleCall)cAnswersAssignment_8_1.eContents().get(0);
		
		//MultiChoiceQuestion:
		//	"add" optional?="optional"? "multi choice question" "text:" text=EString ("requires:" requires=Dependency)?
		//	"answers:" answers+=Answer ("," answers+=Answer)*;
		public ParserRule getRule() { return rule; }

		//"add" optional?="optional"? "multi choice question" "text:" text=EString ("requires:" requires=Dependency)? "answers:"
		//answers+=Answer ("," answers+=Answer)*
		public Group getGroup() { return cGroup; }

		//"add"
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }

		//optional?="optional"?
		public Assignment getOptionalAssignment_1() { return cOptionalAssignment_1; }

		//"optional"
		public Keyword getOptionalOptionalKeyword_1_0() { return cOptionalOptionalKeyword_1_0; }

		//"multi choice question"
		public Keyword getMultiChoiceQuestionKeyword_2() { return cMultiChoiceQuestionKeyword_2; }

		//"text:"
		public Keyword getTextKeyword_3() { return cTextKeyword_3; }

		//text=EString
		public Assignment getTextAssignment_4() { return cTextAssignment_4; }

		//EString
		public RuleCall getTextEStringParserRuleCall_4_0() { return cTextEStringParserRuleCall_4_0; }

		//("requires:" requires=Dependency)?
		public Group getGroup_5() { return cGroup_5; }

		//"requires:"
		public Keyword getRequiresKeyword_5_0() { return cRequiresKeyword_5_0; }

		//requires=Dependency
		public Assignment getRequiresAssignment_5_1() { return cRequiresAssignment_5_1; }

		//Dependency
		public RuleCall getRequiresDependencyParserRuleCall_5_1_0() { return cRequiresDependencyParserRuleCall_5_1_0; }

		//"answers:"
		public Keyword getAnswersKeyword_6() { return cAnswersKeyword_6; }

		//answers+=Answer
		public Assignment getAnswersAssignment_7() { return cAnswersAssignment_7; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_7_0() { return cAnswersAnswerParserRuleCall_7_0; }

		//("," answers+=Answer)*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//answers+=Answer
		public Assignment getAnswersAssignment_8_1() { return cAnswersAssignment_8_1; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_8_1_0() { return cAnswersAnswerParserRuleCall_8_1_0; }
	}

	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLhsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLhsDependencyParserRuleCall_1_0 = (RuleCall)cLhsAssignment_1.eContents().get(0);
		private final Keyword cAndKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRhsDependencyParserRuleCall_3_0 = (RuleCall)cRhsAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//And:
		//	"(" lhs=Dependency "and" rhs=Dependency ")";
		public ParserRule getRule() { return rule; }

		//"(" lhs=Dependency "and" rhs=Dependency ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//lhs=Dependency
		public Assignment getLhsAssignment_1() { return cLhsAssignment_1; }

		//Dependency
		public RuleCall getLhsDependencyParserRuleCall_1_0() { return cLhsDependencyParserRuleCall_1_0; }

		//"and"
		public Keyword getAndKeyword_2() { return cAndKeyword_2; }

		//rhs=Dependency
		public Assignment getRhsAssignment_3() { return cRhsAssignment_3; }

		//Dependency
		public RuleCall getRhsDependencyParserRuleCall_3_0() { return cRhsDependencyParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOrKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLhsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLhsDependencyParserRuleCall_3_0 = (RuleCall)cLhsAssignment_3.eContents().get(0);
		private final Keyword cRhsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRhsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRhsDependencyParserRuleCall_5_0 = (RuleCall)cRhsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Or:
		//	"Or" "{" "lhs" lhs=Dependency "rhs" rhs=Dependency "}";
		public ParserRule getRule() { return rule; }

		//"Or" "{" "lhs" lhs=Dependency "rhs" rhs=Dependency "}"
		public Group getGroup() { return cGroup; }

		//"Or"
		public Keyword getOrKeyword_0() { return cOrKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"lhs"
		public Keyword getLhsKeyword_2() { return cLhsKeyword_2; }

		//lhs=Dependency
		public Assignment getLhsAssignment_3() { return cLhsAssignment_3; }

		//Dependency
		public RuleCall getLhsDependencyParserRuleCall_3_0() { return cLhsDependencyParserRuleCall_3_0; }

		//"rhs"
		public Keyword getRhsKeyword_4() { return cRhsKeyword_4; }

		//rhs=Dependency
		public Assignment getRhsAssignment_5() { return cRhsAssignment_5; }

		//Dependency
		public RuleCall getRhsDependencyParserRuleCall_5_0() { return cRhsDependencyParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class AnswerRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnswerRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnswerRefKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRefersKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRefersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cRefersAnswerCrossReference_3_0 = (CrossReference)cRefersAssignment_3.eContents().get(0);
		private final RuleCall cRefersAnswerEStringParserRuleCall_3_0_1 = (RuleCall)cRefersAnswerCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AnswerRef:
		//	"AnswerRef" "{" "refers" refers=[Answer|EString] "}";
		public ParserRule getRule() { return rule; }

		//"AnswerRef" "{" "refers" refers=[Answer|EString] "}"
		public Group getGroup() { return cGroup; }

		//"AnswerRef"
		public Keyword getAnswerRefKeyword_0() { return cAnswerRefKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"refers"
		public Keyword getRefersKeyword_2() { return cRefersKeyword_2; }

		//refers=[Answer|EString]
		public Assignment getRefersAssignment_3() { return cRefersAssignment_3; }

		//[Answer|EString]
		public CrossReference getRefersAnswerCrossReference_3_0() { return cRefersAnswerCrossReference_3_0; }

		//EString
		public RuleCall getRefersAnswerEStringParserRuleCall_3_0_1() { return cRefersAnswerEStringParserRuleCall_3_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class ChoiceAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ChoiceAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSelectedAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cSelectedSelectedKeyword_0_0 = (Keyword)cSelectedAssignment_0.eContents().get(0);
		private final Keyword cChoiceAnswerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextEStringParserRuleCall_4_0 = (RuleCall)cTextAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ChoiceAnswer:
		//	selected?="selected" "ChoiceAnswer" "{" "text" text=EString "}";
		public ParserRule getRule() { return rule; }

		//selected?="selected" "ChoiceAnswer" "{" "text" text=EString "}"
		public Group getGroup() { return cGroup; }

		//selected?="selected"
		public Assignment getSelectedAssignment_0() { return cSelectedAssignment_0; }

		//"selected"
		public Keyword getSelectedSelectedKeyword_0_0() { return cSelectedSelectedKeyword_0_0; }

		//"ChoiceAnswer"
		public Keyword getChoiceAnswerKeyword_1() { return cChoiceAnswerKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"text"
		public Keyword getTextKeyword_3() { return cTextKeyword_3; }

		//text=EString
		public Assignment getTextAssignment_4() { return cTextAssignment_4; }

		//EString
		public RuleCall getTextEStringParserRuleCall_4_0() { return cTextEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class FreetextAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FreetextAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFreetextAnswerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextEStringParserRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Keyword cInputKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cInputAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cInputEStringParserRuleCall_5_0 = (RuleCall)cInputAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//FreetextAnswer:
		//	"FreetextAnswer" "{" "text" text=EString "input" input=EString "}";
		public ParserRule getRule() { return rule; }

		//"FreetextAnswer" "{" "text" text=EString "input" input=EString "}"
		public Group getGroup() { return cGroup; }

		//"FreetextAnswer"
		public Keyword getFreetextAnswerKeyword_0() { return cFreetextAnswerKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"text"
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }

		//text=EString
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }

		//EString
		public RuleCall getTextEStringParserRuleCall_3_0() { return cTextEStringParserRuleCall_3_0; }

		//"input"
		public Keyword getInputKeyword_4() { return cInputKeyword_4; }

		//input=EString
		public Assignment getInputAssignment_5() { return cInputAssignment_5; }

		//EString
		public RuleCall getInputEStringParserRuleCall_5_0() { return cInputEStringParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private SurveyElements pSurvey;
	private PageElements pPage;
	private QuestionElements pQuestion;
	private DependencyElements pDependency;
	private AnswerElements pAnswer;
	private EStringElements pEString;
	private QuestionPageElements pQuestionPage;
	private DescriptionPageElements pDescriptionPage;
	private ResultPageElements pResultPage;
	private EBooleanElements pEBoolean;
	private FreetextQuestionElements pFreetextQuestion;
	private SingleChoiceQuestionElements pSingleChoiceQuestion;
	private MultiChoiceQuestionElements pMultiChoiceQuestion;
	private AndElements pAnd;
	private OrElements pOr;
	private AnswerRefElements pAnswerRef;
	private ChoiceAnswerElements pChoiceAnswer;
	private FreetextAnswerElements pFreetextAnswer;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public SurveyDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.itu.smdp.group19.SurveyDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Survey:
	//	"start survey" "title:" title=EString "pages:" pages+=Page ("," pages+=Page)* "end survey";
	public SurveyElements getSurveyAccess() {
		return (pSurvey != null) ? pSurvey : (pSurvey = new SurveyElements());
	}
	
	public ParserRule getSurveyRule() {
		return getSurveyAccess().getRule();
	}

	//Page:
	//	QuestionPage | DescriptionPage | ResultPage;
	public PageElements getPageAccess() {
		return (pPage != null) ? pPage : (pPage = new PageElements());
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//Question:
	//	FreetextQuestion | SingleChoiceQuestion | MultiChoiceQuestion;
	public QuestionElements getQuestionAccess() {
		return (pQuestion != null) ? pQuestion : (pQuestion = new QuestionElements());
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}

	//Dependency:
	//	And | Or | AnswerRef;
	public DependencyElements getDependencyAccess() {
		return (pDependency != null) ? pDependency : (pDependency = new DependencyElements());
	}
	
	public ParserRule getDependencyRule() {
		return getDependencyAccess().getRule();
	}

	//Answer:
	//	ChoiceAnswer | FreetextAnswer;
	public AnswerElements getAnswerAccess() {
		return (pAnswer != null) ? pAnswer : (pAnswer = new AnswerElements());
	}
	
	public ParserRule getAnswerRule() {
		return getAnswerAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	////Page_Impl returns Page:
	////	'Page'
	////	'{'
	////		'title' title=EString
	////		('text' text=EString)?
	////	'}';
	//QuestionPage:
	//	"add question page" "title:" title=EString ("text:" text=EString)? "questions:" questions+=Question (","
	//	questions+=Question)*;
	public QuestionPageElements getQuestionPageAccess() {
		return (pQuestionPage != null) ? pQuestionPage : (pQuestionPage = new QuestionPageElements());
	}
	
	public ParserRule getQuestionPageRule() {
		return getQuestionPageAccess().getRule();
	}

	//DescriptionPage:
	//	"add description page" "title:" title=EString ("text:" text=EString)?;
	public DescriptionPageElements getDescriptionPageAccess() {
		return (pDescriptionPage != null) ? pDescriptionPage : (pDescriptionPage = new DescriptionPageElements());
	}
	
	public ParserRule getDescriptionPageRule() {
		return getDescriptionPageAccess().getRule();
	}

	//ResultPage:
	//	"add result page" "title:" title=EString ("text:" text=EString)?;
	public ResultPageElements getResultPageAccess() {
		return (pResultPage != null) ? pResultPage : (pResultPage = new ResultPageElements());
	}
	
	public ParserRule getResultPageRule() {
		return getResultPageAccess().getRule();
	}

	////Question_Impl returns Question:
	////	optional?='optional'
	////	'Question'
	////	'{'
	////	'text' text=EString
	////	('requires' requires=Dependency)?
	////	'}';
	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//FreetextQuestion:
	//	"add" optional?="optional"? "freetext question" "text:" text=EString ("requires:" requires=Dependency)? "answers:"
	//	answers=FreetextAnswer;
	public FreetextQuestionElements getFreetextQuestionAccess() {
		return (pFreetextQuestion != null) ? pFreetextQuestion : (pFreetextQuestion = new FreetextQuestionElements());
	}
	
	public ParserRule getFreetextQuestionRule() {
		return getFreetextQuestionAccess().getRule();
	}

	//SingleChoiceQuestion:
	//	"add" optional?="optional"? "single choice question" "text:" text=EString ("requires:" requires=Dependency)?
	//	"answers:" answers+=Answer ("," answers+=Answer)*;
	public SingleChoiceQuestionElements getSingleChoiceQuestionAccess() {
		return (pSingleChoiceQuestion != null) ? pSingleChoiceQuestion : (pSingleChoiceQuestion = new SingleChoiceQuestionElements());
	}
	
	public ParserRule getSingleChoiceQuestionRule() {
		return getSingleChoiceQuestionAccess().getRule();
	}

	//MultiChoiceQuestion:
	//	"add" optional?="optional"? "multi choice question" "text:" text=EString ("requires:" requires=Dependency)?
	//	"answers:" answers+=Answer ("," answers+=Answer)*;
	public MultiChoiceQuestionElements getMultiChoiceQuestionAccess() {
		return (pMultiChoiceQuestion != null) ? pMultiChoiceQuestion : (pMultiChoiceQuestion = new MultiChoiceQuestionElements());
	}
	
	public ParserRule getMultiChoiceQuestionRule() {
		return getMultiChoiceQuestionAccess().getRule();
	}

	//And:
	//	"(" lhs=Dependency "and" rhs=Dependency ")";
	public AndElements getAndAccess() {
		return (pAnd != null) ? pAnd : (pAnd = new AndElements());
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}

	//Or:
	//	"Or" "{" "lhs" lhs=Dependency "rhs" rhs=Dependency "}";
	public OrElements getOrAccess() {
		return (pOr != null) ? pOr : (pOr = new OrElements());
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}

	//AnswerRef:
	//	"AnswerRef" "{" "refers" refers=[Answer|EString] "}";
	public AnswerRefElements getAnswerRefAccess() {
		return (pAnswerRef != null) ? pAnswerRef : (pAnswerRef = new AnswerRefElements());
	}
	
	public ParserRule getAnswerRefRule() {
		return getAnswerRefAccess().getRule();
	}

	//ChoiceAnswer:
	//	selected?="selected" "ChoiceAnswer" "{" "text" text=EString "}";
	public ChoiceAnswerElements getChoiceAnswerAccess() {
		return (pChoiceAnswer != null) ? pChoiceAnswer : (pChoiceAnswer = new ChoiceAnswerElements());
	}
	
	public ParserRule getChoiceAnswerRule() {
		return getChoiceAnswerAccess().getRule();
	}

	//FreetextAnswer:
	//	"FreetextAnswer" "{" "text" text=EString "input" input=EString "}";
	public FreetextAnswerElements getFreetextAnswerAccess() {
		return (pFreetextAnswer != null) ? pFreetextAnswer : (pFreetextAnswer = new FreetextAnswerElements());
	}
	
	public ParserRule getFreetextAnswerRule() {
		return getFreetextAnswerAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
