/**
 * generated by Xtext
 */
package dk.itu.smdp.group19.validation;

import dk.itu.smdp.group19.validation.AbstractSurveyDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SurveyDSLValidator extends AbstractSurveyDSLValidator {
}
