/**
 * generated by Xtext
 */
package dk.itu.smdp.group19.serializer;

import dk.itu.smdp.group19.serializer.AbstractSurveyDSLSemanticSequencer;

@SuppressWarnings("all")
public class SurveyDSLSemanticSequencer extends AbstractSurveyDSLSemanticSequencer {
}
