/**
 * generated by Xtext
 */
package dk.itu.smdp.group19.serializer;

import dk.itu.smdp.group19.serializer.AbstractSurveyDSLSyntacticSequencer;

@SuppressWarnings("all")
public class SurveyDSLSyntacticSequencer extends AbstractSurveyDSLSyntacticSequencer {
}
