/*
 * generated by Xtext
 */
package dk.itu.smdp.group19.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SurveyDSLUiModule extends dk.itu.smdp.group19.ui.AbstractSurveyDSLUiModule {
	public SurveyDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
