/*
 * generated by Xtext
 */
package dk.itu.smdp.group19;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SurveyDSLRuntimeModule extends dk.itu.smdp.group19.AbstractSurveyDSLRuntimeModule {

}
